# Disabling sudo moves build to the Container Based Infrastructure on Travis CI
sudo: false

language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - android-27
    - build-tools-27.0.1
    - extra-android-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-android-18

script:
  - ./gradlew clean build --stacktrace

before_install:
  - chmod +x gradlew

notifications:
  email: true

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle